from typing import List

import pytest

from awesome_python_leetcode._3838_weighted_word_mapping import Solution


@pytest.mark.parametrize(
    argnames=["words", "weights", "expected"],
    argvalues=[
        (
            ["abcd", "def", "xyz"],
            [
                5,
                3,
                12,
                14,
                1,
                2,
                3,
                2,
                10,
                6,
                6,
                9,
                7,
                8,
                7,
                10,
                8,
                9,
                6,
                9,
                9,
                8,
                3,
                7,
                7,
                2,
            ],
            "rij",
        ),
        (
            ["a", "b", "c"],
            [
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
            ],
            "yyy",
        ),
        (
            ["abcd"],
            [
                7,
                5,
                3,
                4,
                3,
                5,
                4,
                9,
                4,
                2,
                2,
                7,
                10,
                2,
                5,
                10,
                6,
                1,
                2,
                2,
                4,
                1,
                3,
                4,
                4,
                5,
            ],
            "g",
        ),
    ],
)
def test_func(words: List[str], weights: List[int], expected: str):
    """Tests the solution of a LeetCode problem."""
    mapped_word = Solution().mapWordWeights(words, weights)
    assert mapped_word == expected
