class Solution:
    """Base class for all LeetCode Problems."""

    def findTheDifference(self, s: str, t: str) -> str:
        """
        You are given two strings s and t.

        String t is generated by random shuffling string s and then add one more letter
        at a random position.

        Return the letter that was added to t.
        """
        result = 0
        for c in s + t:
            result ^= ord(c)
        return chr(result)
